version: '3.9'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  postgres:
    image: postgres:alpine3.17
    environment:
      POSTGRES_DB: fast_api_2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data